name: deploy to firebase hosting (dev)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        env:
          DOT_ENV_FILE: ${{ secrets.DOT_ENV_PROD }}
        run: |
          echo $DOT_ENV_DEV > .env
          yarn
          yarn build

      - uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_PROD }}
